print("***do'konimizga xush kelibsiz***")
print("do'kondagi maxsulotlar:olma-5000so'm non-6000so'm yog-20000so'm shakar-20000")
olma=int(input("necham kg olma olasiz<<"))
non=int(input("nechta non olasiz<<"))
yog=int(input("necham dona yog olasiz<<"))
shakar=int(input("nechta kg shakar olasiz<<"))
natija=olma*5000+non*6000+yog*20000+shakar*20000
print("siz",olma,"kg olma oldingiz")
print("siz",non,"dona non oldingiz")
print("siz",yog,"dona yog oldingiz")
print("siz",shakar,"kg shakar oldingiz")
print("jammi summa",natija,"so'm")
print("xaridingiz uchun raxmat")
print("yana do'konimizga kelib turing **raxmat**")